from __future__ import annotations

import json

from ..models import ArchitectureArtifact, PrototypeContext, RequirementArtifact


def _config_json(context: PrototypeContext) -> str:
    payload = {
        "product_name": context.product_name,
        "product_slug": context.product_slug,
        "entity_label_singular": context.entity_label_singular,
        "entity_label_plural": context.entity_label_plural,
        "entity_collection_path": context.entity_collection_path,
        "field_definitions": [
            {
                "name": field.name,
                "field_type": field.field_type,
                "description": field.description,
                "required": field.required,
                "default": field.default,
            }
            for field in context.field_definitions
        ],
        "capabilities": context.capabilities,
        "constraints": context.constraints,
    }
    return json.dumps(payload, indent=4)


def render_surface_files(
    requirements: RequirementArtifact,
    architecture: ArchitectureArtifact,
) -> dict[str, str]:
    context = requirements.context
    config_json = _config_json(context)
    readme = f"""# {context.product_name}

This prototype was generated by the autonomous builder.

## What It Does

- Accepts and validates new {context.entity_label_plural}
- Lists existing {context.entity_label_plural}
- Returns details for one {context.entity_label_singular}
- Exposes metadata for future UI clients

## Run

```bash
python -m app.server
```

The server listens on `http://127.0.0.1:8000`.

## Endpoints

- `GET /health`
- `GET /metadata`
- `GET /{context.entity_collection_path}`
- `POST /{context.entity_collection_path}`
- `GET /{context.entity_collection_path}/<id>`

## Architectural Notes

The runtime uses an in-memory repository for determinism, but the architecture artifact defines a production persistence target:

`{architecture.database_schema[0].name}`
"""
    config = f'''"""Product-specific schema and capability metadata."""

from __future__ import annotations

import json


PRODUCT_CONFIG = json.loads(
    """
{config_json}
    """
)
'''
    init_file = '"""Generated prototype application."""\n'
    return {
        "README.md": readme,
        "app/__init__.py": init_file,
        "app/config.py": config,
    }


def render_domain_files(requirements: RequirementArtifact) -> dict[str, str]:
    context = requirements.context
    models = '''"""Shared transport-neutral models for the generated prototype."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


class ValidationError(ValueError):
    """Raised when an incoming payload does not satisfy the generated schema."""


@dataclass(slots=True)
class Record:
    id: str
    created_at: str
    payload: dict[str, Any]


@dataclass(slots=True)
class Response:
    status_code: int
    body: dict[str, Any]
'''
    repository = '''"""Repository boundary for generated prototypes."""

from __future__ import annotations

from .models import Record


class InMemoryRepository:
    """Simple repository adapter kept explicit so it can be replaced later."""

    def __init__(self) -> None:
        self._records: dict[str, Record] = {}

    def create(self, record: Record) -> Record:
        self._records[record.id] = record
        return record

    def list(self) -> list[Record]:
        return list(self._records.values())

    def get(self, record_id: str) -> Record | None:
        return self._records.get(record_id)
'''
    service = f'''"""Application service for schema-driven prototypes."""

from __future__ import annotations

from datetime import datetime, timezone
import uuid

from .config import PRODUCT_CONFIG
from .models import Record, ValidationError
from .repository import InMemoryRepository


class PrototypeService:
    """Coordinates validation and persistence around the generated schema."""

    def __init__(self, repository: InMemoryRepository | None = None) -> None:
        self.repository = repository or InMemoryRepository()
        self.fields = PRODUCT_CONFIG["field_definitions"]

    def _validate(self, payload: dict[str, object]) -> dict[str, object]:
        validated: dict[str, object] = {{}}
        for field in self.fields:
            name = field["name"]
            field_type = field["field_type"]
            required = field["required"]
            default = field["default"]
            if name not in payload or payload[name] in (None, ""):
                if default is not None:
                    validated[name] = default
                    continue
                if required:
                    raise ValidationError(f"Missing required field: {{name}}")
                continue
            value = payload[name]
            if field_type == "int" and not isinstance(value, int):
                raise ValidationError(f"Field {{name}} must be an integer")
            if field_type == "str" and not isinstance(value, str):
                raise ValidationError(f"Field {{name}} must be a string")
            validated[name] = value
        return validated

    def create_record(self, payload: dict[str, object]) -> Record:
        validated = self._validate(payload)
        record = Record(
            id=str(uuid.uuid4()),
            created_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
            payload=validated,
        )
        return self.repository.create(record)

    def list_records(self) -> list[Record]:
        return self.repository.list()

    def get_record(self, record_id: str) -> Record | None:
        return self.repository.get(record_id)
'''
    return {
        "app/models.py": models,
        "app/repository.py": repository,
        "app/service.py": service,
    }


def render_delivery_files(requirements: RequirementArtifact) -> dict[str, str]:
    context = requirements.context
    api = '''"""Request router for the generated prototype."""

from __future__ import annotations

from dataclasses import asdict
from typing import Any

from .config import PRODUCT_CONFIG
from .models import Response, ValidationError
from .service import PrototypeService


class ApiRouter:
    def __init__(self, service: PrototypeService | None = None) -> None:
        self.service = service or PrototypeService()

    def handle(self, method: str, path: str, payload: dict[str, Any] | None = None) -> Response:
        collection_path = f"/{PRODUCT_CONFIG['entity_collection_path']}"
        if method == "GET" and path == "/health":
            return Response(200, {"status": "ok", "product": PRODUCT_CONFIG["product_name"]})
        if method == "GET" and path == "/metadata":
            return Response(
                200,
                {
                    "product_name": PRODUCT_CONFIG["product_name"],
                    "entity_collection": PRODUCT_CONFIG["entity_collection_path"],
                    "fields": PRODUCT_CONFIG["field_definitions"],
                    "capabilities": PRODUCT_CONFIG["capabilities"],
                },
            )
        if method == "GET" and path == collection_path:
            records = [asdict(record) for record in self.service.list_records()]
            return Response(200, {"items": records, "count": len(records)})
        if method == "POST" and path == collection_path:
            try:
                record = self.service.create_record(payload or {})
            except ValidationError as exc:
                return Response(400, {"error": str(exc)})
            return Response(201, {"id": record.id, "record": asdict(record)})
        if method == "GET" and path.startswith(f"{collection_path}/"):
            record_id = path.split("/")[-1]
            record = self.service.get_record(record_id)
            if record is None:
                return Response(404, {"error": "Not found"})
            return Response(200, {"item": asdict(record)})
        return Response(404, {"error": "Route not found"})
'''
    server = '''"""HTTP transport for the generated prototype."""

from __future__ import annotations

from http.server import BaseHTTPRequestHandler, HTTPServer
import json

from .api import ApiRouter


class RequestHandler(BaseHTTPRequestHandler):
    router = ApiRouter()

    def _send(self, status_code: int, body: dict[str, object]) -> None:
        encoded = json.dumps(body).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def do_GET(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler contract
        response = self.router.handle("GET", self.path)
        self._send(response.status_code, response.body)

    def do_POST(self) -> None:  # noqa: N802 - BaseHTTPRequestHandler contract
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length) if length else b"{}"
        payload = json.loads(raw.decode("utf-8"))
        response = self.router.handle("POST", self.path, payload)
        self._send(response.status_code, response.body)

    def log_message(self, format: str, *args: object) -> None:
        # The generated service is quiet by default so CI logs stay readable.
        return


def serve(host: str = "127.0.0.1", port: int = 8000) -> None:
    HTTPServer((host, port), RequestHandler).serve_forever()


if __name__ == "__main__":
    serve()
'''
    return {
        "app/api.py": api,
        "app/server.py": server,
    }


def render_files(
    requirements: RequirementArtifact,
    architecture: ArchitectureArtifact,
) -> dict[str, str]:
    rendered: dict[str, str] = {}
    for partial in (
        render_surface_files(requirements, architecture),
        render_domain_files(requirements),
        render_delivery_files(requirements),
    ):
        rendered.update(partial)
    return rendered
